---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=minimun BITSUN_TRAVIS=2.4.6
  - EMBER_TRY_SCENARIO=ember-release BITSUN_TRAVIS=release
  - EMBER_TRY_SCENARIO=ember-beta BITSUN_TRAVIS=beta
  - EMBER_TRY_SCENARIO=ember-canary BITSUN_TRAVIS=canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
  #- npm test